### ISSUE TITLE
Laravel Vapor - HTTP/2 stream 15 was not closed cleanly before end of the underlying stream in 

### ISSUE THREAD

**Issue by ryangittings** [laravel-notification-channels/apn#140]
Hey all,

I'm getting an issue in Vapor that I can't recreate locally. Stack trace attached:

```Exception: HTTP/2 stream 15 was not closed cleanly before end of the underlying stream in 
Exception: HTTP/2 stream 15 was not closed cleanly before end of the underlying stream in /var/task/vendor/edamov/pushok/src/Client.php:161
Stack trace:
#0 /var/task/vendor/laravel-notification-channels/apn/src/ApnChannel.php(79): Pushok\Client->push()
#1 /var/task/vendor/laravel-notification-channels/apn/src/ApnChannel.php(58): NotificationChannels\Apn\ApnChannel->sendNotifications(Object(Pushok\Client), Object(NotificationChannels\Apn\ApnMessage), Array)
#2 /var/task/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): NotificationChannels\Apn\ApnChannel->send(Object(App\Models\User), Object(App\Notifications\NewEpisode))```

Thank you!

**Comment by dwightwatson** [comment]
Looks like this is an issue with [`pushok`](https://github.com/edamov/pushok) which is the library we use under the hood to send notifications with APN. I wonder if the issue is with `pushok` or something that Vapor is doing. Either way, I don't think it's something we can address in this package.

**Comment by ryangittings** [comment]
That's fair enough! Probably worth me raising an issue there then :) thanks for the quick reply!!
